name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # to push commit to gh-pages behind the scenes
      pages: write         # to deploy to Pages
      id-token: write      # required for OIDC
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build   # creates the dist/ folder

      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist         # tell Pages where the build output lives

      - uses: actions/deploy-pages@v2   # publishes the artifact
